"""Mapped[] definitions

Revision ID: 16b5644c0a3a
Revises: 71aa79713a2a
Create Date: 2026-07-06 17:52:17.876813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b5644c0a3a'
down_revision: Union[str, Sequence[str], None] = '71aa79713a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bins', schema=None) as batch_op:
        batch_op.alter_column('coverpoint_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('coverpoints', schema=None) as batch_op:
        batch_op.alter_column('run_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('coverage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.alter_column('checks',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('overall_coverage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('overall_coverage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
        batch_op.alter_column('checks',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('coverpoints', schema=None) as batch_op:
        batch_op.alter_column('coverage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
        batch_op.alter_column('run_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('bins', schema=None) as batch_op:
        batch_op.alter_column('coverpoint_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table(
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('coverpoint_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=True),
    sa.Column('hits', sa.INTEGER(), nullable=False),
    sa.Column('hit', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['coverpoint_id'], ['coverpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
