"""cascading delete via sql

Revision ID: 2d0dcf91c089
Revises: 
Create Date: 2026-07-04 21:21:38.111651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0dcf91c089'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('run_date', sa.DateTime(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('checks', sa.Integer(), nullable=True),
    sa.Column('overall_coverage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coverpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('coverage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coverpoint_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('hit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['coverpoint_id'], ['coverpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bins')
    op.drop_table('coverpoints')
    op.drop_table('runs')
    # ### end Alembic commands ###
